server:
  port: 8020
  
spring:
 
  application:   #定义服务名称
    name: consumer-user
                   #是否显示IP和端口
    

    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8020                #定义微服务的名称
    prefer-ip-address: true  
feign:
  hystrix: 
    enabled: true   #启动熔断机制   